Tasks/134 arreglo visual ejercicios
fitmeapp-ispp/fitmeapp-frontend pull request #164
Opened 2022-03-31 09:53 UTC by angtordom1

2022-04-01 10:10 UTC, quiquesm requested changes
Todo más centrado y el texto se ve mucho mejor. Se ha encontrado el siguiente problema:

- Utilizando la aplicación web a una resolución de 2560 x 1440 píxeles, el texto explicativo de la imagen del "BUSCADOR DE EJERCICIOS" aparece a un lado de la imagen en lugar de aparecer bajo la misma. Sería óptimo que siempre apareciese debajo.

![image](https://user-images.githubusercontent.com/57001244/161243028-f9f6ac44-7639-4c29-a7e0-22d8768c0774.png)

2022-04-02 19:57 UTC, gonlalle approved these changes

2022-04-02 21:07 UTC, geniusbat approved these changes

2022-04-02 21:18 UTC, quiquesm approved these changes

2022-04-03 18:22 UTC, beallasai approved these changes

2022-04-04 00:26 UTC, merged